export const items = [
  { link: 'https://gotoo.co/demo/acer/ana-knuwan/', title: '永生花', image: 'works-50', info: '2024 作品' },
  { link: 'https://gotoo.co/demo/acer/web/homyn/member.html', title: '好命命理會員系統', image: 'works-49', info: '2023 作品' },
  { link: 'https://gotoo.co/demo/acer/web/cana/', title: 'cana', image: 'works-48', info: '2023 作品' },
  { link: 'https://hungji0201.github.io/liupeanut/#/', title: '劉記花生', image: 'works-47', info: '2023 作品 (Vue)' },
  { link: 'https://www.klk.com.tw/', title: 'klk', image: 'works-46', info: '2022 作品' },
  { link: 'https://www.eyebrow.tw/', title: 'eyebrow', image: 'works-45', info: '2022 作品' },
  { link: 'https://www.zhong-tu.com.tw/', title: '鹿鹿茶香', image: 'works-44', info: '2022 作品' },
  { link: 'https://eijo2.fourfuns.com.tw/dentalhsieh/page.html', title: '2022台中市農會螢火蟲', image: 'works-43', info: '2022 作品' },
  { link: '#', title: 'shenfong', image: 'works-42', info: '2022 作品' },
  { link: 'https://www.easy-fashion.com.tw/', title: '衣世代', image: 'works-41', info: '2022 作品' },
  { link: 'https://eijo2.fourfuns.com.tw/wanheng/', title: 'wanheng', image: 'works-40', info: '2022 作品' },
  { link: 'https://www.g-tek.com.tw/', title: '環宇光電', image: 'works-39', info: '2022 作品' },
  { link: 'https://eijo2.fourfuns.com.tw/KT/', title: 'KT', image: 'works-38', info: '2022 作品' },
  { link: 'https://eijo2.fourfuns.com.tw/agc/', title: 'agc', image: 'works-37', info: '2022 作品' },
  { link: 'https://eijo2.fourfuns.com.tw/sungo/', title: 'sungo', image: 'works-36', info: '2022 作品' },
  { link: 'https://www.ycpackaging.com/zh-Hant', title: '鈺創美學', image: 'works-35', info: '2022 作品' },
  { link: 'https://www.idigi.tw/pcid/index.html', title: '磐成設計', image: 'works-34', info: '2022 作品' },
  { link: 'https://www.asiantech.com.tw/', title: 'asiantech', image: 'works-33', info: '2021 作品' },
  { link: 'https://www.england-dental.com.tw/', title: '英倫牙醫', image: 'works-32', info: '2021 作品' },
  { link: 'https://www.conica.com.tw/', title: 'conica', image: 'works-31', info: '2021 作品' },
  { link: 'https://www.meow-pet.com/', title: 'meow', image: 'works-30', info: '2021 作品' },
  { link: 'https://eijo2.fourfuns.com.tw/niwi/', title: 'niwi', image: 'works-29', info: '2021 作品' },
  { link: 'https://www.jing-cheau.com.tw/', title: 'jing cheau', image: 'works-28', info: '2021 作品' },
  { link: 'https://www.seculok.com/', title: 'seculok', image: 'works-27', info: '2021 作品' },
  { link: 'https://eijo2.fourfuns.com.tw/FutureWafer/', title: 'FutureWafer', image: 'works-26', info: '2021 作品' },
  { link: 'https://www.dr-chiu.com/', title: 'dr-chiu', image: 'works-25', info: '2021 作品' },
  { link: 'https://www.piao-i.com/', title: '飄逸杯', image: 'works-24', info: '2021 作品' },
  { link: 'https://www.idigi.tw/miaoli/', title: '政府 - 苗栗縣政府建管便民服務資訊網', image: 'works-23', info: '2021 作品' },
  { link: 'https://www.idigi.tw/cpami/', title: '政府 - 內政部營建署', image: 'works-22', info: '2021 作品' },
  { link: 'https://www.nafertino.com.tw/', title: 'nafertino', image: 'works-21', info: '2020 作品' },
  { link: 'https://www.high-lacquer.com.tw/', title: 'LEADER', image: 'works-20', info: '2020 作品' },
  { link: 'https://www.ppi-4safe.com/', title: '4safe', image: 'works-19', info: '2020 作品' },
  { link: 'https://eijo2.fourfuns.com.tw/hung-long/', title: 'hung long', image: 'works-18', info: '2020 作品' },
  { link: 'https://eijo2.fourfuns.com.tw/weipower/', title: 'weipower', image: 'works-17', info: '2020 作品' },
  { link: 'https://eijo2.fourfuns.com.tw/CLN/', title: 'CLN', image: 'works-16', info: '2020 作品' },
  { link: 'https://www.tccl.com.tw/', title: 'tccl', image: 'works-15', info: '2020 作品' },
  { link: 'https://www.aplex.com/', title: 'aplex', image: 'works-14', info: '2020 作品' },
  { link: 'https://www.idigi.tw/SHIN-PO/', title: '新保生活關懷', image: 'works-13', info: '2020 作品' },
  { link: 'https://www.idigi.tw/publicworks_tainan/', title: '政府 - 台南市政府工務局建築管理科', image: 'works-12', info: '2020 作品' },
  { link: 'https://www.linkdd.com.tw/', title: '靜藏設計', image: 'works-11', info: '2019 作品' },
  { link: 'https://www.herb-tea.com.tw/', title: 'Herb Tea', image: 'works-10', info: '2019 作品' },
  { link: 'https://eijo2.fourfuns.com.tw/copywriter/', title: '文案的美', image: 'works-09', info: '2019 作品' },
  { link: 'https://eijo2.fourfuns.com.tw/FOURIERS/', title: 'FOURIERS', image: 'works-08', info: '2019 作品' },
  { link: '#', title: 'adam', image: 'works-07', info: '2018 作品' },
  { link: 'https://www.marcella.com.tw/', title: 'marcella', image: 'works-06', info: '2018 作品' },
  { link: 'https://www.navallihill.com/', title: 'navallihill', image: 'works-05', info: '2018 作品' },
  { link: '#', title: 'pekoe', image: 'works-04', info: '2017 - 2018 作品' },
  { link: 'https://www.yilan.com.tw/', title: 'yilan', image: 'works-03', info: '2017 - 2018 作品' },
  { link: '#', title: '林果良品', image: 'works-02', info: '2017 - 2018 作品' },
  { link: 'https://www.feltmaking.com.tw/', title: '羊毛氈手創館', image: 'works-01', info: '2016 作品' }
];